export const INQUIRY_STATUS = {
  FRESH: 'FRESH',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  CANCELED: 'CANCELED',
  ON_HOLD: 'ON_HOLD',
  AWAITING_INFORMATION: 'AWAITING_INFORMATION',
  ERROR: 'ERROR'
} as const;
export type InquiryStatus = typeof INQUIRY_STATUS[keyof typeof INQUIRY_STATUS];
