// Export all interfaces
export * from './IHotel';
export * from './IHotelBooking';
export * from './IUser';
export * from './IHotelUser';
export * from './IBookingUser';
export * from './IRoom';
export * from './IRoomBooking';
export * from './IPackageBooking';
export * from './ILead';
export * from './IInquiry';
export * from './IExpense';
export * from './IIncomeSource';
export * from './IConfig';
export * from './ITransporter';
export * from './IVehicle';
export * from './IItinerary';

// Export Base Interfaces (Pure Types)
export * from './base/IHotelBase';
export * from './base/IHotelBookingBase';
export * from './base/IUserBase';
export * from './base/IHotelUserBase';
export * from './base/IBookingUserBase';
export * from './base/IRoomBase';
export * from './base/IRoomBookingBase';
export * from './base/IPackageBookingBase';
export * from './base/ILeadBase';
export * from './base/IInquiryBase';
export * from './base/IExpenseBase';
export * from './base/IIncomeSourceBase';
export * from './base/IConfigBase';
export * from './base/ITransporterBase';
export * from './base/IVehicleBase';
export * from './base/IItineraryBase';
